default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  # socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DB_NAME'] %>
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  host:  <%= ENV['PRODUCTION_DB_HOST'] %>
  port:  <%= ENV['PRODUCTION_DB_PORT'] %>
