default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  # socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE'] %>
  username: <%= ENV['PRODUCTION_USERNAME'] %>
  password: <%= ENV['PRODUCTION_PASSWORD'] %>
  host:  <%= ENV['PRODUCTION_HOST'] %>
